wip: Django ReST Framework
justquick/django-activity-stream pull request #503
Opened 2022-03-01 02:16 UTC by justquick

- Dynamic serializers and viewsets for the registered models in the actstream.registry
- Default config for Action/Follow
- Views to match (most) streams in the action manager
- Ability to view your own actions
- Custom serializer, viewset and permission options in settings
- Related field evaluation using `rest-framework-generic-relations`

2022-05-20 13:23 UTC, auvipy commented on runtests/requirements.txt
> +Django>=4.0
not even django 3.2 lts? or we will target to  4-4.2 versions to be minimal?

2022-05-30 12:26 UTC, mofe23 commented
If i try to install from this branch instead from pypi i get an ImportError.

Adding `actstream.drf` in `setup.py` resolves the error for me, see this [commit](https://github.com/mofe23/django-activity-stream/commit/376ed392e9530626f982d9479deb6f2376e3a0f6) on my fork:
``` python
      packages=['actstream',
                'actstream.drf',
                'actstream.migrations',
                'actstream.templatetags',
                'actstream.tests',
                ],
```

2022-05-30 13:53 UTC, mofe23 requested changes
Im currently in the process of trying this PR, will add findings here if more occure

If i try to install from this branch instead of using pypi, i get an ImportError on startup.

Adding `actstream.drf` in `setup.py` resolves the error for me, see this [commit](https://github.com/mofe23/django-activity-stream/commit/376ed392e9530626f982d9479deb6f2376e3a0f6) on my fork:
``` python
      packages=['actstream',
                'actstream.drf',
                'actstream.migrations',
                'actstream.templatetags',
                'actstream.tests',
                ],
```

2022-05-30 13:53 UTC, mofe23 commented on actstream/urls.py
> +        path('api/', include(SchemaExtender(router).urls)),
Remove dependency on SchemaeExtender from testapp.

2022-08-15 09:46 UTC, auvipy commented
is there any work remain from your side?

2022-08-16 23:48 UTC, justquick commented
i need to see how dependent this needs to be on drf_spectacular.... it's a great feature but should be optional. id like to publish the output schema api explorer it generates somewhere but it shouldnt b required when running tests or anything else. those parts also need some work but can probably wait

2022-10-15 09:16 UTC, justquick commented
im really tempted to merge this now but there are a couple things lacking. this really needs better tests and documentation. also we should push the openapi standard and provide a redoc site iamo. here's a run i did for the actstream drf api spec.

https://justquick.io/django-activity-stream/redoc.html?

2022-11-05 12:31 UTC, auvipy commented
I checked the doc, what more you intended to complete?

2022-11-20 00:08 UTC, justquick commented
we need to have a guide in the django-activity-stream documentation about how to use drf in actstream. just a page in the docs describing how to access it is enough. ill take a hack at something

i also want to strip the spectacular stuff out of the test app. just seems overkill and confusing. will add it in a later release

2022-11-20 18:06 UTC, justquick commented
there are also changes to the `ACTSTREAM_SETTINGS` that add a `DRF` section which also needs documenting. hoping to finish this up soon

2023-02-11 02:08 UTC, merged

2023-02-11 02:09 UTC, justquick commented
decided to rip off the bandaid and put this into main. please check it out and if there arent any issues then ill cut a 2.0 release